## 测一测你是什么品种的仓鼠
  请按最后分值综合得出结果（单选）

## 如果你的仓鼠宝宝不小心从你的手心摔在了地板上，你先会？
<Strong>A. </Strong>自责+1分    B.心疼+10分    C.内心毫无波澜+15分

## 你把养的仓鼠当成你的
<Strong>A. </Strong>家人+1       B.宠物+5     C.玩具+10

## 看到网上有渣养仓鼠的人（不是虐鼠），你会
<Strong>A. </Strong>事不关己，高高挂起+2   B劝说他好好养仓鼠+5   C上去就是一顿臭骂+10

## 如果买了一只不听话也非常怕人的仓鼠，你会
<Strong>A. </Strong>送人+3    B.养下去+4    C放生+9

## 你最喜欢以下哪种仓鼠呢
<Strong>A. </Strong>肥胖毛多手感好+2    B.不怕人，傻大胆+4   C.品相好，稀有毛色+6
